apiVersion: v1
kind: Pod
metadata:
  name: init-test
  labels:
    app.kubernetes.io/name: myapp
spec:
  initContainers:
    - name: init-cont
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          "echo 'init cont started'; sleep 10; echo 'init cont end....'",
        ]
  containers:
    - name: main-cont
      image: busybox:latest
      command:
        [
          "sh",
          "-c",
          "while true; do echo 'main cont started' >> /var/log/app.log; sleep 5; done",
        ]
      volumeMounts:
        - name: shared-log
          mountPath: /var/log
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "500m"
    - name: sidecar-cont
      image: busybox:latest
      command: ["sh", "-c", "tail -f /var/log/app.log"]
      volumeMounts:
        - name: shared-log
          mountPath: /var/log
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "500m"
  volumes: 
    - name: shared-log
      emptyDir: {}

# sh -c = “run the following string as a shell command.”
# Without -c, the shell expects a script file, not an inline command.