apiVersion: v1
kind: Namespace
metadata:
  name: resources

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: resources
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi


# Explaning Resources Quota
# resources:
#   requests: (minimum Required)
#     cpu:
#     memory:
#   limits: (maximum Limit,do not provide, more than this)
#     cpu:
#     memory:
