apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5



# Enable metrics-server using cmnd >> minikube addons enable metrics-server

# The HPA uses the formula:
# desiredReplicas = currentReplicas × (currentCPUUtilization / targetCPUUtilization)