apiVersion: v1
kind: Namespace
metadata:
  name: apache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-apache-app
  template:
    metadata:
      labels:
        app: my-apache-app
    spec:
      containers:
        - name: myapp
          image: httpd:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
spec:
  selector:
    app: my-apache-app
  ports:
    - port: 80
      targetPort: 80

