apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: practice-k8
  labels:
    app: my-nginx-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
