apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: rolling-update-ns
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:alpine
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
# nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: rolling-update-ns
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
