apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data

    # can be different as per requirements.
    # persistentVolumeReclaimPolicy: Retain, Delete
    # storageClassName: slow, local-storage
    # mountOptions:
    #   - hard
    #   - nfsvers=4.1
    # nfs:
    #   path: /tmp
    #   server: 172.17.0.2
