apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: practice-k8
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
