apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: multi-app
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
