apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: notes-app-namespace
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
