apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: v1
      mirror:
          host: reviews
          subset: v2
# Now, all traffic that goes to reviews v1 will also be mirrored to reviews v2 without affecting the user experience.
#  This allows testing the new version with real-world traffic before fully switching over.