apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  clusterIP: None
  selector:
    app: my-sql-app
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
# Services in Stateful set are headless services which means:
# 1. Cluster IP is not assigned to the service
# 2. Service is used for DNS resolution of the pods in the StatefulSet
# This service will not get exposed, it is for internal use, as we don't expose our database along with our application, simply like that


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: my-sql-app
  template:
    metadata:
      labels:
        app: my-sql-app
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: devops
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

# We can notice that Statefulset binds together
# 1. A Headless service for DNS resolution
# 2. A Persistent volume claim template for persistent storage
# 3. A Pod template for the application container (common for others too)
# for each Pod 

# For MYSQL or databases - env variables are necessary step
# there are some extra steps if you need multi-replicas (NOT ADDED YET) -> changing replicas to 1 for now