kind: Namespace
apiVersion: v1
metadata:
  name: secure-app-2

---
apiVersion: v1
kind: Pod
metadata:
  name: node-app
  namespace: secure-app-2
  labels:
    app: node-app
spec:
  containers:
  - name: node
    image: node:latest
    command: ["node", "-e", "require('http').createServer((req,res)=>res.end('Hello')).listen(3000)"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: secure-app-2
spec:
  selector:
    app: node-app
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-app
  namespace: secure-app-2
  labels:
    app: mysql-app
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "password"
    resources:
      requests:
        memory: "256Mi"
        cpu: "1000m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
    ports:
      - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: secure-app-2
spec:
  selector:
    app: mysql-app
  ports:
  - port: 3306
    targetPort: 3306

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-node-on-mysql
  namespace: secure-app-2
spec:
  podSelector:
    matchLabels:
      app: mysql-app
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: node-app
      ports:
      - protocol: TCP
        port: 3306
# it means traffic is allowed on mysql-app from node-app at port 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
  namespace: secure-app-2
spec:
  podSelector: {}
  policyTypes:
  - Egress
# it means no pod can initiate a connection to any other pod

# the end result of both network policy will be 
# 1. mysql-app allows inbound connections on port 3306 if the source is a node-app pod.
# 2. However, the deny-egress policy blocks all egress traffic, including from node-app.
# 3. Since node-app cannot initiate any outbound connections, it cannot start a TCP session to mysql-app.
# so connection can't be made
