apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  namespace: blue-green-ns
  labels:
    app: my-app
    version: green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: apache-image
        image: httpd:2.4
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: blue-green-ns
spec:
  selector:
    app: my-app
    version: green
  ports:
  - port: 80
    targetPort: 80
